### ISSUE TITLE
scraper until presentation for EthIndia

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-cir#4]
## `@todo`
* [x] update folder structure of all stored contracts
* [x] update server on digital ocean with API to see the contracts that are already downloaded
* [x] add dat to the server and keep it running, which means:
    * [x] install dat (`npm install -g dat`)
    * [x] go to the contracts server `cd ./sourcecode`
    * [x] start dat server with `dat share .` (and on server restart make sure it runs `dat share .` again
* [x] make sure dat keeps on running (maybe using pm2?)
* [x] on your laptop, install dat (`npm install -g dat`) and try to clone the dataset to see if it works
  * `dat clone dat://ba54302dc0186acd7c53cb00709217c73d4f679431822f1a57bddc068d96cb74`
* [x] add additional API to server `/daturl` to get the dat address on which the content gets shared
    * so that `curl https://<digitaloceanserver ip>/daturl` returns e.g. `dat://230f2903j9sj49jaf9323f`
* [x] also http://104.248.146.46:3001/count does not tell me how many contracts are in the database
* [x] http://104.248.146.46:3001/daturl doesnt work - it does not show me the dat address i can use to clone the data

---
**new folder structure for storing contracts**
* /sourcecode
   * /23
     * /49
       * /234982094ug2409jg3480jgw
       * /23a4982094ug2409jg3480jg
    * /79
       * /237982094ug2409jg3480jgw
   * /3a
     * /4t
       * /3a4t4wsyhe5y55eg2409jg34
     * /bt
       * /3abt4wsyhe5y55eg2409jg34
     * /xt
       * /3axt4wsyhe5y55eg2409jg34
   * /7z
     * /ai
       * /7zairj7dhthdhe5y55eg2409j
       * /7zairj7dhthdhe5y55eg2409j
     * /fi
       * /7zfiaarj7dhthdhe5y55eg240
     * /ui
       * /7zuirj7dgdgdhthdhe5y55eg
