### ISSUE TITLE
p2p publish data archive

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-cir#5]
## `@todo`
* [ ] store all and add more smart contract source codes to dat and publish on DHT
    * [ ] create a dat archive and store all contracts in the archive and add more in the future
    * [ ] publish archive to `<specific-not-yet-decided-topic>` using **dat sdk**

---
