### ISSUE TITLE
maintain always up-to-date list of proxy servers

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-cir#6]
## `@todo`
* [ ] create a `get-proxy-server.js` with the logic to fetch proxy server IP's
* [ ] add http api to the `https://<get-proxy-server.js>:<port>/proxylist`
    * [ ] on request, read `proxylist.json` and check timestamp
      * [ ] if timestamp is old, fetch new proxies first and save them in proxylist.json with new timestamp
      * [ ] if timestamp is good, return `proxylist.json` content
* [ ] when fetching new `<proxy ip>`s:
   * delete old `proxylist.json` and create new `proxylist.json` with new `timestamp`
   * [ ] for each `<proxy ip>` it gets, try to make a request to e.g. `google.com` and
      * if it succeeds store `<proxy ip>` in `proxylist.json`
      * if it fails, ignore and throw away the `<proxy ip>`
* [ ] make sure it get's started and restarted whenever the digital ocean server starts or restarts

---
