### ISSUE TITLE
AST/type/data analysis

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-cir#7]
## `@todo`
* [ ] write AST/type/data analyser module to find compatible version range for type/data/...
* [ ] write AST/type/data analyser module to find a list of all dependencies in items
* [ ] write AST/type/data analyser module to find all items in the exact order they have been defined
    * https://github.com/ethereum/solidity/issues/2731
* [ ] [`datdot-tcir#2` - AST/type/data import statement analysis and content hash replacement](https://github.com/playproject-io/datdot-tcir/issues/2)
* [ ] brainstorm about useful AST/type/data analyser modules and add them to this list
    * https://chriseth.github.io/notes/talks/trust_gap_meetup/#/16 bytecode metadata

---
